### ISSUE TITLE
IssuesPdfHelperTest fails when run in isolationv Defect #28233

### ISSUE THREAD

**Issue by kevinyoutha** [kevinyoutha/redmine#1]
The IssuesPdfHelperTest test fails, when starting it in isolation. It's missing the neccessary fixture definitions. Depending on the random test order, this might also lead to errors, when running the whole test suite.
![issue](https://user-images.githubusercontent.com/26203503/38314049-6904dbe2-37f3-11e8-8931-325a7175e300.png)

**Comment by morenard** [comment]
the test associated to this feature fail. Could you look at this
